### ISSUE TITLE
(question) License 

### ISSUE THREAD

**Issue by ebachard** [pijushbarik/videoreader-ffmpeg#1]
Hello,

Thank you very much for sharing your code, very interesting. 

Can you please tell me the license you are using I was not able to find one.

Thanks in advance,
Eric Bachard

**Comment by pijushbarik** [comment]
Hi @ebachard , thanks for your interest in my code. I have added a MIT license to my repo.
Good luck!

**Comment by ebachard** [comment]
Thanks a lot for your reactivity ! 

If you are interested, I tested your code, and added some fixes (Linux only).

If you are interested, I can create a pull request (the code will be under MIT license of course)

**Comment by ebachard** [comment]
@pijushbarik 

Just for your information : https://github.com/ebachard/videoreader-ffmpeg/commit/8fd4b8afc03b8fbec5b4c2239d04c44505147a7b

avdevice_register_all() is mandatory to make the /dev/video*  to be detected + link with libavutil

**Comment by pijushbarik** [comment]
Please do that. Create a pull request with the fix and I will merge that. I actually wrote and tested this code only in Linux, so the Linux only fix is okay.

I think the avdevice_register_all() call will enable to use USB cams as well.
